subprojects {
    apply plugin: "java-library"
    apply plugin: "idea"

    group = "${mod_group}"

    repositories {
        maven { url = "https://maven.terraformersmc.com/" }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(25)
        withSourcesJar()
    }
}