subprojects {
    apply plugin: 'idea'
    apply plugin: 'java-library'

    group = 'dngnrr.aspengrove'

    repositories {
        mavenCentral()
        maven { name = "Modrinth"; url = "https://api.modrinth.com/maven" }
        maven { name = "TerraformersMC"; url = "https://maven.terraformersmc.com/" }
        maven { name = "NeoForged"; url = "https://maven.neoforged.net/releases/" }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        withSourcesJar()
    }
}