# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Mod
mod_id=aspengrove
mod_name=Aspen Grove
mod_version=2.2.0
mod_group=dngnrr.aspengrove
mod_description=Add new blocks and biome!
mod_license=MIT
java_version=25
homepage_link=https://modrinth.com/mod/aspengrove
sources_link=https://github.com/dungeonerr/Aspen-grove
issues_link=https://github.com/dungeonerr/Aspen-grove/issues
mod_version_common=2.2.0-common

# Dependencies
minecraft_version=26.3-snapshot-10
min_minecraft_version=26.3-alpha.10
biolith_version=3.7.0-alpha.2

//# NeoForge
//neoforge_loader_version=26.2.0.32-beta
//neoforge_loader_version_range=[1,)
//mod_version_neoforge=2.2.0-neoforge

# Fabric
min_fabric_loader_version=0.19.0
fabric_loader_version=0.19.3
fabric_api_version=0.158.3+26.3
loom_version=1.17-SNAPSHOT
mod_version_fabric=2.2.0-fabric
