# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Mod
mod_id=aspengrove
mod_name=Aspen Grove
mod_version=1.1.6-1.21.1
mod_group=dngnrr.aspengrove
mod_description=Add new blocks and biome!
mod_license=GPL-3.0-or-later
java_version=21
homepage_link=https://modrinth.com/mod/aspengrove
sources_link=https://github.com/dungeonerr/Aspen-grove
issues_link=https://github.com/dungeonerr/Aspen-grove/issues
mod_version_common=1.1.6-1.21.1-common

# Dependencies
minecraft_version=1.21.1
biolith_version=3.0.10

# NeoForge
neoforge_loader_version=21.1.231
neoforge_loader_version_range=[1,)
ottyg_version_neoforge=1.21.1-5.3.2-NeoForge
mod_version_neoforge=1.1.6-1.21.1-neoforge

# Fabric
fabric_loader_version=0.16.0
fabric_api_version=0.116.12+1.21.1
ottyg_version_fabric=1.21.1-5.3.2-Fabric
loom_version=1.16-SNAPSHOT
mod_version_fabric=1.1.6-1.21.1-fabric